defaults:
  - default
  - _self_

config:
  task_labels_dir: ???
  max_seq_len: ${_generation_context_size}
  seq_sampling_strategy: TO_END
  padding_side: LEFT
  include_window_last_observed_in_schema: True
