input_dir: ${oc.env:RAW_MEDS_DIR}
output_dir: ${oc.env:MTD_INPUT_DIR}

stages:
  - reshard_to_split:
      n_subjects_per_shard: 10000
  - add_time_derived_measurements:
      age: null
      time_of_day: null
      timeline_tokens:
        time_unit: years
  - count_codes:
      aggregations:
        - code/n_occurrences
        - code/n_subjects
    _base_stage: aggregate_code_metadata
  - filter_measurements:
      _match_revise:
        - _matcher:
            time:
              present: False
        - _matcher:
            code:
              regex: "MEDS_DEATH.*|MEDS_BIRTH.*|.*ADMISSION.*|.*DISCHARGE.*|.*REGISTRATION.*|.*TIME.*"
        - _matcher:
            time:
              present: True
          min_subjects_per_code: ${oc.decode:${oc.env:MIN_SUBJECTS_PER_CODE,1000}}
  - filter_subjects:
      min_events_per_subject: ${oc.decode:${oc.env:MIN_EVENTS_PER_SUBJECT,10}}
      min_measurements_per_subject: null
  - bin_numeric_values:
      do_drop_numeric_value: True
      custom_bins_filepath: ${oc.env:NUMERIC_CUSTOM_BINS_FP,null}
