defaults:
  - _preprocess
  - _self_
input_dir: ${oc.env:RAW_MEDS_DIR}
cohort_dir: ${oc.env:MTD_INPUT_DIR}
stages:
  - add_time_interval_tokens
  - count_codes
  - filter_measurements
  - filter_subjects
  - fit_quantile_binning
  - quantile_binning

stage_configs:
  add_time_interval_tokens:
    _script: "MEICAR_add_time_interval_tokens"
    time_delta:
      time_unit: years
  count_codes:
    _script: MEDS_transform-aggregate_code_metadata
    aggregations:
      - code/n_occurrences
      - code/n_subjects
  filter_measurements:
    _match_revise:
      - _matcher:
          time:
            present: False
      - _matcher:
          code:
            regex: "MEDS_DEATH.*|MEDS_BIRTH.*|.*ADMISSION.*|.*DISCHARGE.*|.*REGISTRATION.*|.*TIME.*"
      - _matcher:
          time:
            present: True
        min_subjects_per_code: ${oc.decode:${oc.env:MIN_SUBJECTS_PER_CODE,1000}}
  filter_subjects:
    min_events_per_subject: ${oc.decode:${oc.env:MIN_EVENTS_PER_SUBJECT,10}}
    min_measurements_per_subject: null
  fit_quantile_binning:
    _script: MEDS_transform-aggregate_code_metadata
    aggregations:
      - code/n_occurrences
      - code/n_subjects
      - name: values/quantiles
        quantiles: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  quantile_binning:
    _script: "MEICAR_quantile_binning"
    custom_quantiles:
      TIME//DELTA//TOKEN:
        values/quantile/1: 0.00000190258 # 1 minute
        values/quantile/2: 0.00000951293 # 5 minutes
        values/quantile/3: 0.00001902587 # 10 minutes
        values/quantile/4: 0.00005707762 # 30 minutes
        values/quantile/5: 0.00011415525 # 1 hour
        values/quantile/6: 0.00034246575 # 3 hours
        values/quantile/7: 0.0006849315 # 6 hours
        values/quantile/8: 0.00136986301 # 12 hours
        values/quantile/9: 0.00273972602 # 1 day
        values/quantile/10: 0.00547945205 # 2 days
        values/quantile/11: 0.0109589041 # 4 days
        values/quantile/12: 0.01917808219 # 7 days
        values/quantile/13: 0.03835616438 # 14 days
        values/quantile/14: 0.08219178082 # 30 days
        values/quantile/15: 0.16438356164 # 60 days
        values/quantile/16: 0.32876712328 # 120 days
        values/quantile/17: 1 # 1 year
        values/quantile/18: 2 # 2 years
        values/quantile/19: 5 # 5 years
        values/quantile/20: 10 # 10 years
        values/quantile/21: 20 # 20 years
        values/quantile/22: 40 # 40 years
