_target_: MEDS_EIC_AR.model.Model

do_demo: False

gpt_kwargs:
  num_hidden_layers: ???
  num_attention_heads: ???
  hidden_size: ???
  intermediate_size: ${prod:${.hidden_size},4}
  max_position_embeddings: ???
  vocab_size: ???
